### ISSUE TITLE
 Semantically order style attributes by default

### ISSUE THREAD

**Issue by Ede123** [scour-project/scour#106]
#105 implemented intuitive ordering of attributes (see issue #60).

Additional we should also order the value of `style` attributes. This should finally ensure a constant output across runs of Scour on the same file. Ordering should probably be done alphabetically.

**Comment by dirk-thomas** [comment]
Do you think a simple "split-on-semicolor, sort, join again" is enough for this? Or do you imagine something more sophisticated in case the values themself contain semicolons?

**Comment by Ede123** [comment]
Yes, I guess that should be sufficient. At least that's what we're doing in `[repairStyle()](https://github.com/scour-project/scour/blob/3929426a5aabbb6819b0d9eb473492e1aa075a7d/scour/scour.py#L1436)`.

Do you have a scenario in mind where this approach might fail?

**Comment by dirk-thomas** [comment]
No, nothing specific. Just thinking... See #107 for the trivial patch.
