### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by Ede123** [scour-project/scour#114]
@oberstet: Is testing for code coverage something we'd want to complement our efforts towards CI?

I doubt it really pays of for a small project, but I'm looking into the topic for the first time and I'm curious enough to spend a bit time on it.

On first look it could definitely help to improve our unittests (a quick investigation with `coverage` revealed some blind spots)...

**Comment by Ede123** [comment]
I just submitted #115 that would take cate of `coverage`.

@oberstet - before I merge:
* Are you fine with automatically running `coverage` and uploading the results to [Codecov](https://codecov.io/)?
* Do we want to integrate codecov in GitHub to check PRs (and if yes with any specific settings or simply the default?)
* Do we want to have those [comments](https://github.com/codecov/support/wiki/Pull-Request-Comments) Codecov creates on pull requests (My PR apparently [already created one](https://github.com/scour-project/scour/pull/115#issuecomment-247737813))?

**Comment by oberstet** [comment]
@Ede123 Yeah, integrating `covreage` into Travis, automatically uploading results and autoadding comments to PR is all desirable IMO. We can steal from https://github.com/crossbario/autobahn-python ..

**Comment by Ede123** [comment]
My PR already does all that.
If you think I missed anything feel free to adjust...
