### ISSUE TITLE
--set-precision 1 is producing "1e1" instead of "10"

### ISSUE THREAD

**Issue by pborunda** [scour-project/scour#132]
Non-scientific is better in this case, so results in 2 bytes instead of 3 bytes

**Comment by Ede123** [comment]
Should be fixed by #133. Feel free to test and report back if I missed some cases.

I'm still doing some investigations, so I hope it's OK for you if reviewing of #131 takes me a bit longer...

**Comment by pborunda** [comment]
yes just confirming that this fix corrected the problem
