### ISSUE TITLE
Leading zero not dropped as expected

### ISSUE THREAD

**Issue by pborunda** [scour-project/scour#137]
"0.4" should collapse to ".4" and
 "-0.4" to "-.4", etc.

Looking at, i would expect the leading zero to drop.
around line 2650 in scour.py
    if not needsRendererWorkaround:
        if len(nonsci) > 2 and nonsci[:2] == '0.':
            nonsci = nonsci[1:]  # remove the 0, leave the dot
        elif len(nonsci) > 3 and nonsci[:3] == '-0.':
nonsci = '-' + nonsci[2:] # remove the 0, leave the minus and dot

**Comment by Ede123** [comment]
You gave yourself the answer...
Use `--no-renderer-workaround` and the zeroes should be stripped

**Comment by pborunda** [comment]
oh, i assumed it was default, thanks!
