### ISSUE TITLE
Determine if "q" and "t" control points work for --set-c-precision

### ISSUE THREAD

**Issue by pborunda** [scour-project/scour#138]
I don't use quadratic Bézier curveto "q" and "t", so not sure of real world example. Should these "q" and "t" control points precision be treated similarly to "c" and "s" with --set-c-precision?

**Comment by Ede123** [comment]
Definitely... Control points in `q Q` have to be reduced in precision too (I noticed that it was missing from #131 but I decided it'd be more efficient if I implemented it myself without bugging you any more - maybe keep this in mind for future PRs, though, as I always prefer PRs that I don't have to rework myself).

I already have code for that in my local repository and will push it once it's ready.
