### ISSUE TITLE
Intermediate nodes and markers LOST

### ISSUE THREAD

**Issue by cfierrob** [scour-project/scour#145]
I was sent here from Inkscape--Bugs.

  Running last Inkscape version under Windows 7.
  1. Added intermediate nodes to 3 straight lines to put on them intermediate markers
  2. Works fine for Inkscape svg
  3. On the same drawing, saved as Optimized svg, the markers on
   * horizontal straight line
   * vertical straight line
  are lost--preserved only on oblique line.
  4. My own impression, after swift look at the text in the optimized svg file: the conversor tries to be too smart by half, AND DELETES ALL THE INTERMEDIATE NODES ON THE HORIZONTAL AND VERTICAL LINES AS UNNECESSARY--WHICH THEY SURELY ARE ... BUT FOR THE MARKERS!!
  5. Instead, and although the middle markers should be exactly the same on all three paths (I even tried to paste style from one to the other two to ensure this) I get three separate <def> ... two of them unused.
The system refuses to let me attach my couple of svg files--saved as Inkscape svg and Optimized svg.
Thanks!

**Comment by Ede123** [comment]
Good catch! Will be fixed soon...

Note to self:
It's due to `h` and `v` commands being collapsed (doesn't happen with e.g. `m` commands.), simple check for markers should suffice.
We could obviously collapse those, too, to save a few bytes in such circumstances!

**Comment by Ede123** [comment]
Fixed in #146 (specifically b7bfb3250afe8cadb61e997c7eae00654c999daa)

This also spawned a lot of other improvements regarding optimization of consecutive straight path segments, so thanks again for the report!
