### ISSUE TITLE
How To Use This In a Python Application?

### ISSUE THREAD

**Issue by leomoon** [scour-project/scour#159]
Hello,

Is there anyway to use Scour in a python script like:
```
import scour
scour('in.svg', 'out.svg')
```

**Comment by Ede123** [comment]
Yes, use something like
```Python
from scour.scour import scourString
out_string = scourString(in_string)
```

Some alternative implementations:
* [Inkscape Scour extension](https://gitlab.com/inkscape/inkscape/blob/master/share/extensions/scour.inkscape.py)
* [Taschenmesser](https://github.com/oberstet/taschenmesser/blob/HEAD/taschenmesser/svg.py)

Long-term goal is to implement a proper API (see #119) that can be called by other scripts to avoid calling internal/undocumented functions.

**Comment by leomoon** [comment]
Thank you. :)
