### ISSUE TITLE
Scour "failed to create process." on Python 3.5.0

### ISSUE THREAD

**Issue by timmyrs** [scour-project/scour#162]
I'm using Python 3.5.0 on Windows 8.1 and I've just installed Scour using pip. However, running Scour results in the message

> failed to create process.

when I run it as admin and normal user, but only with Python 3.5.0 — with Python 2.7.14 it works.

**Comment by Ede123** [comment]
Works fine in Python 3.6.1.

Are you able to run other Python Scripts created by pip?

I suspect a more fundamental issue in Python/pip unrelated to Scour here...

**Comment by timmyrs** [comment]
I've already replaced Python 3 with Python 2 and I'm not that big of a Python user that I would know any other Python projects.

**Comment by Ede123** [comment]
Well, unless you're able to test with another version of Python / an updated pip to narrow down the cause, there's not much we can do...
