### ISSUE TITLE
path processiong wrong

### ISSUE THREAD

**Issue by JoKalliauer** [scour-project/scour#163]
Processiong [File:Envelope_string_art.svg](https://commons.wikimedia.org/wiki/File:Envelope_string_art.svg) with
> $ scour [Envelope_string_art.svg](https://upload.wikimedia.org/wikipedia/commons/6/6a/Envelope_string_art.svg) output.svg

connects a corner to the origin, instead of closing the rectangle:
[input.svg.txt](https://github.com/scour-project/scour/files/1671066/input.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="600" height="480" xmlns="http://www.w3.org/2000/svg">
 <path d="m108.5 408h441.3m-441.3 0v-371.9m0 0v371.9h441.3v-371.9z" fill="none" stroke="#000"/>
</svg>

```
![input](https://user-images.githubusercontent.com/15687581/35482143-3edbfa58-0431-11e8-8aaa-122581419e50.png)

The output is:
[output.svg.txt](https://github.com/scour-project/scour/files/1671067/output.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="600" height="480" xmlns="http://www.w3.org/2000/svg">
 <path d="m108.5 408h441.3m-441.3 0v-371.9 371.9h441.3v-371.9z" fill="none" stroke="#000"/>
</svg>

```
![output](https://user-images.githubusercontent.com/15687581/35482149-530c595a-0431-11e8-90ac-7e11bd7402e4.png)

so
`d="m108.5 408h441.3m-441.3 0v-371.9m0 0v371.9h441.3v-371.9z"` is changed to:
`d="m108.5 408h441.3m-441.3 0v-371.9 371.9h441.3v-371.9z"`

**Comment by nthykier** [comment]
I have traced this issue to the following part of cleanPath:

```python
                if cmd == 'm':
                    # remove m0,0 segments
                    if pathIndex > 0 and data[0] == data[i + 1] == 0:
                        # 'm0,0 x,y' can be replaces with 'lx,y',
                        # except the first m which is a required absolute moveto
                        path[pathIndex] = ('l', data[2:])
                        _num_path_segments_removed += 1
                    else:  # else skip move coordinate
                        i = 2
```

The bug disappears if we special case on "len(data) == 2" and insist on keeping the "m0,0" command in that case.  However, that breaks trips the following test case:

```python
class PathEmptyMove(unittest.TestCase):

    def runTest(self):
        doc = scourXmlFile('unittests/path-empty-move.svg')
        self.assertEqual(doc.getElementsByTagName('path')[0].getAttribute('d'), 'm100 100 200 100z')
        self.assertEqual(doc.getElementsByTagName('path')[1].getAttribute('d'), 'm100 100v200l100 100z')
```

Test data:

```xml
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg">
  <path d="m100 100 l200 100 m0 0z" />
  <path d="m100 100 v200 m0 0 100 100z" />
</svg>
```

The first path ends with "m0 0z" and the test case expects this to be reduced into "z" (the second path should be unaffected by this change).  From what I gathered from the [SVG 1.1 standard], the "m0 0" will create a new subpath and "z" will close the current subpath (i.e. draw a lone from the current position to the beginning of the subpath).  I.e. a "m0 0z" is basically a no op (or a dot; not quite sure which).  

As I understand it, this makes "Xm0 0z" and "Xz" are two different things.  The former creates "X" and then an "empty" subpath while the latter creates X and then closes it by drawing a straight line from the current position to the initial point of X.  In other words, if I understood the spec correctly the current test is wrong (it should either leave "m0 0z" alone or also remove the "z"; not entirely sure which of the two are correct though).

If we agree on that point, I will look into providing a patch for this bug.  Alternatively, I will need help figuring out when "m0 0" can be removed and when it cannot.

[SVG 1.1 standard]: https://www.w3.org/TR/SVG/paths.html

**Comment by nthykier** [comment]
Ok, I devised a test case that shows that we cannot arbitrarily remove "m0 0".

The original:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg width="600" height="480" xmlns="http://www.w3.org/2000/svg">
  <path d="m150 240h200m0 0 150 150v-300z" fill="none" stroke="#000"/>
</svg>
```

The scour'ed version:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg width="600" height="480" xmlns="http://www.w3.org/2000/svg">
 <path d="m150 240h200l150 150v-300z" fill="none" stroke="#000"/>
</svg>
```

The difference difference in the xml is that a "m0 0 150 150" is replaced by "l150 150". The original draws a line and a triangle while the scour'ed version draws a deformed rectangle. From this I suspect that it is unsafe to rewrite "m0 0" if the subpath ends with a z/Z command. I.e.

 * `... m0 0 150 150 ... z` is unsafe
 * `... m0 0 150 150 ... mX Y ... z` _might_ be rewritable to `l150 150 ... mX Y ... z`

**Comment by nthykier** [comment]
Forgot to mention: The special case `m0 0z` is also problematic to rewrite at all times.  If a path ends with `m0 0z` then it is a no-op.  Likewise, a `m0 0zm...` can also be reduced to `m...`.  However, `m0 0zl...` should be rewritten as `m0 0l...` (i.e. the "z" is redundant, but "m0 0" is not).
