### ISSUE TITLE
--enable-id-stripping aswell as --shorten-ids changes colour

### ISSUE THREAD

**Issue by JoKalliauer** [scour-project/scour#164]
Processing [https://commons.wikimedia.org/wiki/File:Test_only.svg](https://commons.wikimedia.org/wiki/File:Test_only.svg) with
> $ scour -i [Test_only.svg](https://upload.wikimedia.org/wikipedia/commons/5/58/Test_only.svg) -o output.svg --enable-id-stripping --shorten-ids

[min.svg.txt](https://github.com/scour-project/scour/files/1712746/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" viewBox="0 0 31 31" xmlns="http://www.w3.org/2000/svg">
 <style type="text/css"><![CDATA[
.group .shape_under_group,
.shape_direct
{
   fill:             #ff0000;
}
.square
{
   fill:             #0000ff !important;
}
.group #square_id
{
   fill:             #0000ff;
}
.force_inherit
{
   fill:             inherit;
}
]]></style>
 <g class="group" transform="translate(-56,-17)">
  <rect id="square_id" class="shape_under_group" x="56" y="17" width="31" height="31" fill="#00f"/>
 </g>
</svg>

```
![min](https://user-images.githubusercontent.com/15687581/36055283-b2c9bfe4-0dfb-11e8-9bf6-9d70b067ae94.png)

leads to
[output.txt](https://github.com/scour-project/scour/files/1712747/output.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg version="1.1" viewBox="0 0 31 31" xmlns="http://www.w3.org/2000/svg">
 <style type="text/css"><![CDATA[
.group .shape_under_group,
.shape_direct
{
   fill:             #ff0000;
}
.square
{
   fill:             #0000ff !important;
}
.group #square_id
{
   fill:             #0000ff;
}
.force_inherit
{
   fill:             inherit;
}
]]></style>
 <g class="group" transform="translate(-56,-17)">
  <rect class="shape_under_group" x="56" y="17" width="31" height="31" fill="#00f"/>
 </g>
</svg>

````
![output](https://user-images.githubusercontent.com/15687581/36055281-ada072ec-0dfb-11e8-98b9-a0a4317f1407.png)

but `id="square_id"` is still needed for the colordefinition in the css.

**Comment by Ede123** [comment]
Symptom of #174.

You can use one of the `--protect-ids-*` options to work around the issue.

**Comment by JoKalliauer** [comment]
another example: (I just found this bugreport, after writing a new one)

##  input
![](https://gitlab.com/inkscape/inbox/uploads/957f2bae45ba1fc3ccd91c013282fbe4/Input.svg)

## output 
![](https://gitlab.com/inkscape/inbox/uploads/6724f268f75c1ca5c9aed4a1ef9b5c64/OutputS.svg)

## copyright

source https://en.wikipedia.org/wiki/File:Comparison_gender_life_expectancy_CIA_factbook.svg

author https://commons.wikimedia.org/wiki/User:Cmglee

license https://creativecommons.org/licenses/by-sa/3.0
