### ISSUE TITLE
scour changes colour (CSS)

### ISSUE THREAD

**Issue by JoKalliauer** [scour-project/scour#176]
Processing https://commons.wikimedia.org/wiki/File:2016_Angola_and_DR_Congo_yellow_fever_outbreak.svg
changes colour:
> $ scour [2016_Angola_and_DR_Congo_yellow_fever_outbreak.svg](https://upload.wikimedia.org/wikipedia/commons/e/e3/2016_Angola_and_DR_Congo_yellow_fever_outbreak.svg) output.svg

Input:
![2016_angola_and_dr_congo_yellow_fever_outbreakn](https://user-images.githubusercontent.com/15687581/37245734-fcb21162-249c-11e8-9d38-e5f34471aefe.png)

Output:
![outputn](https://user-images.githubusercontent.com/15687581/37245735-029504b8-249d-11e8-94ba-5610aca1bcb2.png)

minimal working example:
Input:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg id="svg20" width="57.249" height="57.119" version="1.1" viewBox="82.992 45.607 56.547 62.09" xmlns="http://www.w3.org/2000/svg">
 <style id="style2" type="text/css">.landxx
{
   fill: #e0e0e0;
}</style>
 <path class="landxx ke" d="m73.956 89.432c-7.828-15.27 2.175-34.73 17.328-40.886 12.51-5.798 28.9-2.052 36.587 9.6848 12.48 17.52 0.604 45.97-20.802 48.959-13.3 1.759-27.35-5.67-33.159-17.803" style="fill:#7b7bff"/>
</svg>
```
![mineinsinrss_](https://user-images.githubusercontent.com/15687581/37245755-59f75c38-249d-11e8-9ab6-d5d000e48c5c.png)

output:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg id="svg20" width="57.249" height="57.119" version="1.1" viewBox="82.992 45.607 56.547 62.09" xmlns="http://www.w3.org/2000/svg">
 <style id="style2" type="text/css">.landxx
{
   fill: #e0e0e0;
}</style>
 <path class="landxx ke" d="m73.956 89.432c-7.828-15.27 2.175-34.73 17.328-40.886 12.51-5.798 28.9-2.052 36.587 9.6848 12.48 17.52 0.604 45.97-20.802 48.959-13.3 1.759-27.35-5.67-33.159-17.803" fill="#7b7bff"/>
</svg>
```
![output](https://user-images.githubusercontent.com/15687581/37245756-5df4972e-249d-11e8-9879-2321e1d50707.png)

The images are created by Inkscape, in Google Chrome and Firefox they look similar.

**Comment by Ede123** [comment]
Yet another symptom of #174 (how many more of those do you want to file? ;-) )

As a workaround you could use `--disable-style-to-xml`

**Comment by JoKalliauer** [comment]
A better minimal example:

scour -i [input.svg.txt](https://github.com/scour-project/scour/files/2425794/input.svg.txt) -o [output.svg.txt](https://github.com/scour-project/scour/files/2425796/output.svg.txt)


# Input
[input.svg.txt](https://github.com/scour-project/scour/files/2425794/input.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
 <style type="text/css">.landxx { fill: #e0e0e0}</style>
 <circle class="landxx cd" cx="50" cy="50" r="45" style="fill:#f00"/>
</svg>
```
![input](https://user-images.githubusercontent.com/15687581/46172561-16ef3280-c2a4-11e8-85af-2cfb107e53d0.png)


# Output
[output.svg.txt](https://github.com/scour-project/scour/files/2425796/output.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
 <style type="text/css">.landxx { fill: #e0e0e0}</style>
 <circle class="landxx cd" cx="50" cy="50" r="45" fill="#f00"/>
</svg>
```
![output](https://user-images.githubusercontent.com/15687581/46172568-1a82b980-c2a4-11e8-917e-d005e0e3dad8.png)


# Difference
` style="fill:#f00"` is changed to ` fill="#f00"`. and it seems that `style=` has a higher priority than `class=`&`<style` and `fill=`has a lower priority, therfore handling conflicting informations can lead to renderdifferences.
![screenshot 2018-09-27 22 25 43 - kopie](https://user-images.githubusercontent.com/15687581/46172737-8e24c680-c2a4-11e8-8266-bc9d156ee6b2.png)
