### ISSUE TITLE
--multipass

### ISSUE THREAD

**Issue by JoKalliauer** [scour-project/scour#195]
Is there an option for multipass?

As in [svgo](https://github.com/svg/svgo/blob/master/README.md#Usage) or in [svgcleaner](https://github.com/RazrFalcon/svgcleaner/issues/142#issuecomment-381055494).

**Comment by Ede123** [comment]
There is not and I tend to consider this kind of brute-force approach as flawed as it means we did not properly optimize something before (see e.g. #186).

For a related issue see #124 (and I think I'll close this one in favor of the earlier report as the issue such an option would be trying to solve is basically what the linked issue is about)

In any case you can always run scour multiple times manually or via a suitable script. As a matter of fact you can even pipe the output on the command line many times through scour with minimum effort:
```sh
scour in.svg | scour | scour | scour -o out.svg
```
