### ISSUE TITLE
Quoted font-family-names get destroyed

### ISSUE THREAD

**Issue by jazzynico** [scour-project/scour#21]
(Original report in https://bugs.launchpad.net/scour/+bug/1514073)

Font-family-names like "'MyriadPro-Regular'" get converted to "&apos;MyriadPro-Regular&apos;" with HTML-Entitys (primary fonts with whitespaces, because single quotation marks are recommended for this by the W3C) if you save as Optimzed SVG. Tested on Windows 7 x64 and Ubuntu latest version.

=====
Inkscape 0.91 r13725
includes Scour 0.26+r220

Also reproduced on Xubuntu 15.10 with Scour 0.31 (as a standalone script).
Test file available in the original report (unfortunately GH doesn't support SVG attachments...).

**Comment by Ede123** [comment]
Fixed in 57f93efc894b1ba4c30e42b549b0081185029c36
Keep an eye open for regressions, since where not escaping quotes ('/") in text nodes and attribute names anymore.
