### ISSUE TITLE
Import history from old repository

### ISSUE THREAD

**Issue by Ede123** [scour-project/scour#23]
I found a possibility ([`git-replace`](https://git-scm.com/docs/git-replace)) to import the full history from the Launchpad repository, **linking** it to the GitHub commit history **without rebasing** (all the recent commits remain unchanged including hashes!)

In fact my fork at https://github.com/Ede123/scour contains the full history right now, see https://github.com/Ede123/scour/commits/39fb9eee021e328261075481a2addbdca2c6cf19.

I'm afraid GitHub does not support replacements in its front-end, so it will not show the combined history. However if one clones the repository locally and executes `git fetch origin 'refs/replace/*:refs/replace/*'` the full history will be available and visible when doing e.g. `git log`

Since GitHub does not allow me to create a PR for this (since there are obviously no changes when comparing):
Shall I describe the necessary steps in detail so someone with write access to the repository can re-do the import?

**Comment by oberstet** [comment]
To be honest, I have never done that before, but I have been bitten by Git tricks modifying history before. So I'm a bit sceptical.

@Ede123 Could you describe the steps that you did? How would be try that here without risking screwing up the whole repo?

@codedread Is this (having complete history here) something you would see as important? You started this code base, so I think you should have final decision on this.

**Comment by Ede123** [comment]
First of all: My approach does not modify history **at all**! That's the beauty of `git-replace`. The current commits remain completely unchanged. The commits from the history are simply added in parallel (i.e. have no connection to the current commits).
Only by using `git-replace` a virtual link between the two separate commit histories is created. This is done by *virtually* replacing one single commit of the current commits with a modified version that includes the the last commit of the old history as a parent.
If one does not fetch this replacement (which is stored in `.git/refs/replace/` as a plain text file) with the command I posted above absolutely nothing will change. If one does fetch the replacement one will have the combined commit history.

For the whole procedure I first followed [this guide](https://astrofloyd.wordpress.com/2012/09/06/convert-bzr-to-git/) to convert the Launchpad bazaar repository to git:

I then followed [this explanation on StackOverflow](http://stackoverflow.com/questions/1220557/how-do-i-prepend-history-to-a-git-repo/1547490#1547490) to create the link using Git replace using the method described in the section *"Using refs/replace/ mechanism"*.

**Comment by Ede123** [comment]
I should add that I already used the history *a lot*, mainly to check whether the issues the unittests just unveiled where regressions of recent changes. Also I use `git blame` a lot to figure out why specific portions of code where written the way they are (often ancient commit messages contain a lot of useful information).

**Comment by codedread** [comment]
I don't have an opinion on how important the history is here.  As long as current maintainers and developers are happy - that sounds great! :)

**Comment by Ede123** [comment]
As this was a freebie I just pushed the replacement to the main repository.

If you want to have the full commit history simply execute the command I already mentioned above:
```sh
git fetch origin 'refs/replace/*:refs/replace/*'
```
