### ISSUE TITLE
Indentation switches don't seem to work

### ISSUE THREAD

**Issue by bulkware** [scour-project/scour#232]
I just installed scour 0.37 using PIP. Tried it for few svg-images, looks promising. The indentation switches don't seem to work. Here is my sample command:

`scour -i soup.svg -o soup-scour.svg --enable-viewboxing --enable-id-stripping --enable-comment-stripping --shorten-ids --indent=space --nindent=2`

The result is a single-lined document without indentation.

**Comment by Ede123** [comment]
The option works for me.

Is it possible your document has the attribute `xml:space="preserve`?

In that case scour is "prohibited" from changing whitespace nodes. However, you can remove the problematic attribute before processing by using the `--strip-xml-space` option.

**Comment by bulkware** [comment]
You are correct, I had that attribute. Now it works as expected.
