### ISSUE TITLE
embedding xlink:href="file:///C:/Pic.png" does not work

### ISSUE THREAD

**Issue by JoKalliauer** [scour-project/scour#236]
I created a svg using inkscape which has ` xlink:href="file:///C:/Users/jkalliau/Desktop/Pic.png"`, but I get the error message `WARNING: Could not open file 'file:/C:/Users/jkalliau/Desktop/Pic.png' for embedding. The raster image will be kept as a reference but might be invalid. (Exception details: <urlopen error [Errno 2] No such file or directory: '/C:/Users/jkalliau/Desktop/Pic.png'>)
` , there is a workaround if I change it to ` xlink:href="file:C:/Users/jkalliau/Desktop/Pic.png"`

I assume scour does not understand `file:///`

### EmbedingBug
[Bug.svg.txt](https://github.com/scour-project/scour/files/3965521/Bug.svg.txt)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg width="395.42pt" height="466.22pt" viewBox="0 0 395.42 466.22" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <image id="image2937" x="2.98" y="5.14" width="389.71" height="454.98" image-rendering="optimizeSpeed" xlink:href="file:///C:/Users/jkalliau/Desktop/Pic.png" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:xlink="http://www.w3.org/1999/xlink" sodipodi:absref="C:\Users\jkalliau\Desktop\Pic.png"/>
</svg>
```

### Workaround
[Workaround.svg.txt](https://github.com/scour-project/scour/files/3965523/Workaround.svg.txt)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg width="395.42pt" height="466.22pt" viewBox="0 0 395.42 466.22" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <image id="image2937" x="2.98" y="5.14" width="389.71" height="454.98" image-rendering="optimizeSpeed" xlink:href="file:C:/Users/jkalliau/Desktop/Pic.png" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:xlink="http://www.w3.org/1999/xlink" sodipodi:absref="C:\Users\jkalliau\Desktop\Pic.png"/>
</svg>
```

**Comment by Ede123** [comment]
Yeah, cross platform path handling is a mess - what is worse is that it's even harder to test.

As a matter of fact it works perfectly fine for me with Python 3.8.3 as provided by the MSYS2 project (mingw-w64 variant), both from cmd.exe as well as MinTTY/bash.

Can you confirm this is still an issue and clarify the python version(s) used?

**Comment by JoKalliauer** [comment]
It works in MingW64 (but not in Cygwin), therefore imho not a scour-problem.

How chan I check which Python Scour is using? (I assume 3.6.9)

**Comment by JoKalliauer** [comment]
Sorry for the delay. I activated my spamfilter 10days ago at the mail-provider and it moved all github/inkscape reports to junk. :-(
