### ISSUE TITLE
 --shorten-ids breaks file and increases file-size

### ISSUE THREAD

**Issue by JoKalliauer** [scour-project/scour#256]
`scour -i input -o output --shorten-ids` breaks file

## Input
[Input.svg](https://gitlab.com/inkscape/inbox/uploads/39f2912ed29ffeb15111f0318672ba2d/Input.svg)
![Input.svg](https://gitlab.com/inkscape/inbox/uploads/39f2912ed29ffeb15111f0318672ba2d/Input.svg)

## Output
[Output.svg](https://gitlab.com/inkscape/inbox/uploads/7b1de555ac8664fc65adcc1de7261810/Output.svg)
![Output.svg](https://gitlab.com/inkscape/inbox/uploads/7b1de555ac8664fc65adcc1de7261810/Output.svg)

## Changes
only ids are changing

The file contains more than 26 references and uses (a-z and A-Z), however scour changes to (a-z and aa-az)

I think there might be somehow an overflow-error in the ids?

PS the files contains **no** CSS

## Source
https://commons.wikimedia.org/wiki/File:Bundesrat_Sitzverteilung.svg

**Comment by Ede123** [comment]
Fixed in https://github.com/scour-project/scour/pull/257

**Comment by JoKalliauer** [comment]
@nthykier : Thanks that solved the breaking of the file
@Ede123 : The file-size still increases, see title (but the main problem is solved)
