### ISSUE TITLE
"Create groups for similar attributes" seems always on

### ISSUE THREAD

**Issue by sunjaxx** [scour-project/scour#265]
I have a SVG with two (ungrouped) paths.

Using "Save as Inkskape SVG" produces:

```
    <g
       id="g3160">
      <path
         style="fill:none;fill-opacity:0.194118;stroke:#ff0000;stroke-width:0.264583;stroke-linejoin:round;stroke-miterlimit:7.70054;stroke-opacity:1"
         d="M 50,60 100,120 M 50,60 V 200 L 100,120"
         id="path3128" />
      <path
         d="M 130.0238,69.547617 150.43452,220.73808 91.470236,213.93451 177.6488,69.547617 Z"
         id="path3150"
         style="fill:none;fill-opacity:0.194118;stroke:#ff0000;stroke-width:0.264583;stroke-linejoin:round;stroke-miterlimit:7.70054;stroke-opacity:1" />
    </g>
```

Save as "optimised SVG" (with the "convert CSS attributes to XLM attributes" option checked and the "collapse groups" and "create groups for similar attributes" **either unchecked or checked**) produces:

```
 <g fill="none" stroke="#f00" stroke-linejoin="round" stroke-miterlimit="7.7005" stroke-width=".26458">
  <path d="m50 60 50 60m-50-60v140l50-80"/>
  <path d="m130.02 69.548 20.411 151.19-58.964-6.8036 86.179-144.39z"/>
 </g>
```

What I'd like to export is:

```
<g>
 <path d="m50 60 50 60m-50-60v140l50-80" fill="none" stroke="#f00" stroke-linejoin="round" stroke-miterlimit="7.7005" stroke-width=".26458"/>
 <path d="m130.02 69.548 20.411 151.19-58.964-6.8036 86.179-144.39z" fill="none" stroke="#f00" stroke-linejoin="round" stroke-miterlimit="7.7005" stroke-width=".26458"/>
</g> 
```

Shouldn't this be the output with "create groups for similar attributes" **unchecked**?

Thanks

**Comment by JoKalliauer** [comment]
@sunjaxx :

"Create groups" means it creates a group, where no group was before

Example:
```svg
<rect fill="red"  width="1" height="2">
<rect fill="red"  width="2" height="1">
```
will create (if enabled)
```xml
<g fill="red">
 <rect width="1" height="2">
 <rect width="2" height="1">
</g>
```
You might want to read https://github.com/scour-project/scour/wiki/Documentation#--create-groups for a more detailed explanation.

## possible Solution/Workaround
You might want to try `--disable-style-to-xml` (in Inkscape it is imho untick "Convert CSS attributes to XML attributes")
>python3 -m scour.scour -i [Input.svg](https://gitlab.com/inkscape/inbox//uploads/c9f5e54a45c3c4ace3a68d9658bf800e/Input.svg) -o [Output.svg](https://gitlab.com/inkscape/inbox//uploads/6287b6c0099288b4acfa14a4c52326f5/Output.svg) --disable-style-to-xml

### Output
[Output.svg](https://gitlab.com/inkscape/inbox//uploads/6287b6c0099288b4acfa14a4c52326f5/Output.svg)
![Output.svg](https://gitlab.com/inkscape/inbox//uploads/6287b6c0099288b4acfa14a4c52326f5/Output.svg)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg id="svg5" width="170.54" height="214.59" version="1.1" viewBox="49.868 59.915 127.9 160.95" xmlns="http://www.w3.org/2000/svg">
 <g id="g3160">
  <path id="path3128" d="m50 60 50 60m-50-60v140l50-80" style="fill:none;stroke-linejoin:round;stroke-miterlimit:7.7005;stroke-width:.26458;stroke:#f00"/>
  <path id="path3150" d="m130.02 69.548 20.411 151.19-58.964-6.8036 86.179-144.39z" style="fill:none;stroke-linejoin:round;stroke-miterlimit:7.7005;stroke-width:.26458;stroke:#f00"/>
 </g>
</svg>
```

**Comment by Ede123** [comment]
I hope the suggested workaround was a viable option.

For Scour I believe this is out-of-scope as it's basically asking to tell scour *not* to optimize the SVG, when the result reported in the first post is actually a perfectly safe optimization.
