### ISSUE TITLE
Support for Sketch

### ISSUE THREAD

**Issue by Eitot** [scour-project/scour#35]
The application [Sketch](http://www.sketchapp.com) is a fairly popular vector application on the Mac. I hope that support could be added at some point. Just for documentary purposes, some Sketch-specific inclusions that would need to be scrubbed (I haven’t found a complete specification yet):
* Namespace: `xmlns:sketch="http://www.bohemiancoding.com/sketch/ns"`
* Header:
 * `<!-- Generator: Sketch X.Y.Z (01234) - http://www.bohemiancoding.com/sketch -->` (will be removed with `--enable-comment-stripping`)
 * `<title>[...]</title>` (title of the exported Sketch object) 
 * `<desc>Created with Sketch.</desc>`
* In Sketch you can create separate pages, which seem to be exported even though they have no purpose in an SVG file anyway. I generally remove it after using Scour and have not encountered any problems as of yet.
```
<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
    <g id="[same as <title>]" sketch:type="MSLayerGroup">
        [...]
    </g>
</g>
``` 
* Sketch-specific attributes:
 * `sketch:alignment` (for `<text>`, not supported natively)
 * `sketch:name` (only seen in `<mask>` so far)
 * `sketch:type` (values: `MSPage`, `MSShapeGroup`, `MSLayerGroup`, `MSTextLayer`)

**Comment by Eitot** [comment]
I just added a pull request. It turns out that adding the namespace “sketch” will take care of the `namespace` attribute in `<svg>` as well as the Sketch-specific attributes. The header is a bit tricky, because `<title>` and `<desc>` have legitimate purposes and the two added `<g>` tags are very specific to Sketch. I am not sure that more could be done.

**Comment by Ede123** [comment]
* Namespace: Resolved with your PR #38 in combination with #14 
* Header: Comments can already be removed as you noted, descriptive elements are covered in issue #38.
* Pages: If I understand your sample correctly you want to remove the `<g>` elements? If you use `--enable-id-stripping` all groups should at least be collapsed into one single group. The last one can not be completely removed as it specifies `fill="none"` (which differs from the default `fill="black"`) and removal of that attribute could therefore change the appearance of the image.
* Sketch-specific attributes: Resolved with your PR #38

I guess we covered everything and can close this issue, or did I miss anything?

**Comment by Eitot** [comment]
Sketch always creates these particular lines of code, just these two parent <g> elements. I suspect, based on the sketch:type attribute, that this mimics the canvas upon which elements are placed when working with Sketch. I was thinking along the lines of a particular workaround for this. However, I of course accept that this is not a nice solution.

**Comment by Ede123** [comment]
Yes, I'm afraid there's not much more we can do with respect to that specific detail.
Even if we *want* to add a program-specific workaround (which we should always avoid) we *can't* remove the enclosing group unless we duplicate the `fill="none"` to all children that inherit this attribute (which is obviously the exact opposite of what we want to achieve).
