### ISSUE TITLE
Support for Inkscape

### ISSUE THREAD

**Issue by Perhelion** [scour-project/scour#39]
The application Inkscape is fairly the most popular free vector application on Linux and Windows. But I found no install support (or instructions) for the actual version (Scour and Inkscape)!?

I have done this now for my self (edited the scour.inkscape.py and installed the modul "six") This was nearly the first time I do something like this (so I'm not an expert).
Frankly, I want that, do not need to do again. I'm a bit wondering about this situation at all, because Scour already exist as Inkscape plugin.

Many thanks anyway to the continuing develop.

**Comment by su-v** [comment]
@Perhelion - updating the version of scour bundled and distributed with Inkscape for the output extension 'Optimized SVG' is tracked by the project 'Inkscape' here:
* Bug #1411149 “[Update the built-in Scour Extension to 0.30](https://bugs.launchpad.net/inkscape/+bug/1411149)”

**Comment by Perhelion** [comment]
@su-v thanks

**Comment by Ede123** [comment]
I updated the Inkscape Scour extension to be compatible with recent versions of the Scour module.
* On Linux machines you have to manually install the Scour module (pypi is the preferred way to do that), so you'll usually have the latest version.
* On Windows Python and the Scour module are bundled with the installer. I updated the included version of Scour and will have an eye on it in the future.

The updated Scour extension will be shipped starting with Inkscape 0.92 which should be released soon. Until then you can use a development build or update you local installation with the updated files.

If there are further questions regarding the implementation of Scour in Inkscape feel free to contact me (I'm active in both projects).
