### ISSUE TITLE
Adjust repo settings for Travis integration

### ISSUE THREAD

**Issue by oberstet** [scour-project/scour#54]
@codedread Hi Jeff, we need your help;)

In [this](https://github.com/codedread/scour/pull/52) Eduard (@Ede123) has added [Travis](https://travis-ci.org/) and [Tox](https://testrun.org/tox/latest/) support. This is for automatically testing installation and unit tests on various Python environments. Eg see the output here https://travis-ci.org/Ede123/scour/builds/120307796

Now, we can make above tests run full automatically on new/modified PRs, and immediately see if there is something bad inside, eg have a look at https://github.com/crossbario/txaio/pull/59 and the test results https://travis-ci.org/crossbario/txaio/builds/118453232

**For Travis integration, this repo needs to be wired up to Travis. This is easy and quick, but can only be done by repo admins.** 

So I would like to ask if you support these efforts?

**If so, you would need an account on https://travis-ci.org/, and then go to "Settings => Webhooks => Add .. Travis"**

**Comment by Ede123** [comment]
Since I just did this step for my fork I can say that it's even easier nowadays:
* Just visit https://travis-ci.org
* There you can "Sign in with GitHub" which automatically authorizes Travis in GitHub via OAuth
* Afterwards you only have to "Flick the repository switch on" in your Travis profile (your repositories will be auto-detected after initial login) which effectively enables Travis build checking and automatically adds said webhook.

**Comment by oberstet** [comment]
@Ede123 The downside of that (automatic) way is that Travis will require a extended permissions on your repo.

**Comment by Ede123** [comment]
That is true, Travis requests the following permissions
* Read org and team membership
* Access commit status
* Access deployment status
* Access user email addresses (read-only)
* Write repository hooks

**Comment by oberstet** [comment]
Oh, nice. This seems to have changed. A write permission to a repository, but specific to repository hooks. If above is the new set of permissions, these are reasonable. So the automatic method is fine in this respect too now.

**Comment by Ede123** [comment]
Hm, seems @codedread is on holiday? (At least that's where I'd be :wink:)

**Comment by oberstet** [comment]
@Ede123 Holidays .. what's that? ;)

Travis CI would be a nice addition to this project. I think it's worth and deserves it. Also, as you already did all the hard work of migrating the unit tests here ..

**Comment by Ede123** [comment]
@oberstet Did you receive my mail regarding transfer of the project to an organization Tobias? (I sent it to the mail address you use in your commits). You could share owner rights with Jeff then...

**Comment by oberstet** [comment]
@Ede123 What is the state of our discussion moving this repo (again) to somewhere else? Did I miss anything? I am open to move it, but please lets make that then the **last** move;)

**Comment by oberstet** [comment]
@Ede123 I am also open to share admin/merge rights with you, as you seem to be motivated and skilled in the area - and me I am drowning in other things ..

**Comment by Ede123** [comment]
Last response by @codedread was, that he will delay the move until he's 
back from holiday (don't know when that is). Otherwise I think we'd be fine.

I'd be happy to support the project, however it would he nice if you could 
still review more complex changes since you obviously are much more 
experienced.

Last but not least I'm on holiday and traveling myself right now, so I 
won't have access to a computer in the next two weeks and you should expect 
delays in my answers.


Am 25. Juli 2016 3:55:20 vorm. schrieb Tobias Oberstein 
<notifications@github.com>:

**Comment by oberstet** [comment]
@Ede123 No worries - have a nice trip!

> Of course I will continue to support/review stuff around. We pretty much depend on Inkscape/Scour for all of our Web sites. It's just that I thought you are much more involved in Inkscape/SVG in general compared to me. And can also act as a "hub" towards Inkscape - which pretty much is the whole reason I got into Scour anyways;) It is important to "connect communities", and for that you need guys involved at both ends ..

**Comment by codedread** [comment]
I'm back from holiday and can help out (or enable folks to move it).  Can
someone clarify what the move is and what I need to do?

I'm the least involved with Scour between us three these days :D

Jeff

**Comment by codedread** [comment]
Ok, figured it out - I have transferred codedread/scour repo to
scour-project/scour.  scour-project is the Github organization that Eduard
and I are in.

**Comment by oberstet** [comment]
@codedread Great, thanks! Could you give me admin rights to the repo?

**Comment by codedread** [comment]
Invite sent

**Comment by oberstet** [comment]
@codedread Mmh, something seem to went wrong .. I didn't get an invite. Usually, you (as an owner/admin) will have a "Settings" tab to the very right/top on the repo. There, go to "Collaborators & Teams" .. there you can configure who has what permissions. I would need to be "Admin" to be able to setup Travis integration and such. Have a look at one of our repos here http://picpaste.com/pics/Bildschirmfoto_vom_2016-07-28_15_27_01-F0fJDkpL.1469712448.png

**Comment by codedread** [comment]
Hi Tobias,

I sent you an invite to the scour-project organization (see screenshot).
Can you look for an invite for that?  I have tried to send it again.

Once you're part of that organization, I will make you an admin so you can
administer all the things (there's only one repo managed by that org, the
scour repo).

Jeff
[image: Screen Shot 2016-07-29 at 11.30.30 AM.png][image: Screen Shot
2016-07-29 at 11.31.36 AM.png]

**Comment by codedread** [comment]
Ok, I also added you explicitly as an Admin of the scour repo:

[image: Screen Shot 2016-07-29 at 11.32.56 AM.png]

**Comment by oberstet** [comment]
@codedread thanks! that workered. I could already review and merge a PR, and also are able to change repo settings - which is needed to setup Travis ..

**Comment by oberstet** [comment]
@codedread @Ede123 alright, I have setup Travis integration .. it'll kick in for each commit pushed. As you can see, something fails for py 2.6: https://travis-ci.org/scour-project/scour/builds/148530565 - so it works! ;)

**Comment by Ede123** [comment]
@oberstet - Yes, the error was introduced in 1a8ece216d4ec9cb4b0eb93aee358d07e9ed7253 (Python 2.6. doesn't like the call of `assertRaises()` in the unittest for [`DocWithFlowtext`](https://github.com/scour-project/scour/commit/1a8ece216d4ec9cb4b0eb93aee358d07e9ed7253#diff-975960277bf7ab4cd7ddf5644929297dR1421)).

Should we fix it or simply drop official support for Python 2.6? Inkscape distributions for Windows will bundle Python 2.7 in future, so my biggest concern is resolved.
Do you know if any common Linux distro still relies on Python 2.6?

**Comment by oberstet** [comment]
@Ede123 I am +1 on dropping 2.6 support. Many major projects already did (eg Twisted).

**Comment by Ede123** [comment]
@oberstet All right, [done](https://github.com/scour-project/scour/commit/df142a2f2248d4dc997d4c19aacf1656f8e42d10).
