### ISSUE TITLE
Consistent formatting of code files

### ISSUE THREAD

**Issue by Ede123** [scour-project/scour#69]
I regularly struggle with different files of the Scour project using different formatting (notably different indenting which is particularly inconvenient in Python).

I'd like to harmonize formatting across source files and adjust at least indentation.
Personally I prefer 4-space indents, but I'm open for suggestions.

Pinging @oberstet since I guess proper code formatting is important to you and you decided on the unusual 3-space indents currently used in `scour.py`.

**Comment by Eitot** [comment]
In addition to indenting, also consider:

- single/double quotes
- lower_case_names/camelCaseNames
- comments as sentences (first word capitalised and full-stop)/comments lower-cased without full-stop
- Usage of multiline comments or not

**Comment by oberstet** [comment]
@Ede123 first, sorry for being unresponsive (I am land under with stuff to do). Rgd code formatting: absolutely! I am ++1 on this.

Rgd 3 spaces: we should fix that and make it 4. I have given up on my personal preference here. There is a coding style standard in Python: PEP8. And regardless of personal preferences, it is better to stick with that (yeah, I have changed my opinion on that).

Rgd best practices in general: we could steal from https://github.com/crossbario/txaio (eg https://github.com/crossbario/txaio/blob/master/Makefile#L29)

txaio is in many respects following Python best practices ..

**Comment by Ede123** [comment]
OK, PR with a lot of reformatting according to PEP 8 is at #113.

I also ran `flake8` which found a lot of minor inconsistencies but also [one real bug](https://github.com/scour-project/scour/pull/113/commits/99363c9089b280ae076992c60dbc638c2cc4c202#diff-f3a786b343df338a105658892b2db4c2R2074) that occured when a path started with an `A` command due to uninitialized variables.

**Comment by oberstet** [comment]
Nice, nice! I think this again is a big step forward making Scour a good Python citizen, following best practices. It'll pay off. Easier to read (because consistent style), easier to maintain.

I also notice you switched to a fix/feature branch workflow .. also good. I should do that as well for future contributions to Scour.

If we agree on that workflow being desirable, we could switch the repo to: "no direct push to master" mode. We can also turn on "all tests must pass before merge" mode. Eg we (Autobahn/Crossbar.io) do that - as many "bigger/significant" Python projects on GitHub. When turning on these things (can be done in repo settings), even repo admins are forced to follow that.

**Comment by oberstet** [comment]
One more note: as soon as this PR is merged, it would be good to integrate flake8 into the automated CI tests (like this https://github.com/crossbario/txaio/blob/master/tox.ini#L42) - because that (combined with the enforcements above) will make sure that no PEP8 violations slip into the code base again ..

**Comment by Ede123** [comment]
Regarding list by @Eitot:
* single/double quotes:<br>I didn't change anything yet but personally I'd stick to the following scheme, which adds an actual meaning to the type of quotes used
   * *double quotes* - (`"`) - are used for strings in a natural language, i.e. help output, warning/error messages, informational output, but also comments (as long as they do not simply use `#`). Basically all strings that are intended to be read by a human (or should be treated as human input)
   * *single quotes* - (`'`) - are used for all other strings, i.e. tag names, property names, regexes, etc. that are used programmatically.
* lower_case_names/camelCaseNames:<br>This is very inconsistent in our code files. I think in the long run we should also try to follow PEP 8 recommendations, but I don't think it's important enough to warrant explicit renaming.
* comments as sentences (first word capitalised and full-stop)/comments lower-cased without full-stop:<br>I honestly don't care. I always try to make comments as short and clear as possible. If "by accident" a complete sentence results I usually add punctuation and capitalization, otherwise I keep it lowercase and unpunctuated.
* Usage of multiline comments or not:<br>As above - clarity is most important and I usually decide what is most suitable as I go. I don't think we should apply strict rules.



@oberstet:
Yes, I use separate branches / PRs for all changes that are a little more complex an might break something. In this way I can allow unit tests to run before merging and it ensures I committed everything correctly (e.g. once I forgot to add an .svg needed by a new unittest).<br>I also like that I can squash my PRs which keeps the history clean while allowing to split the PR itself in smaller logical parts that are easier to review (e.g. bugfix + some refactoring + unittest + update to history.md).

However I wouldn't switch to "no direct push to master" since for trivial changes (e.g. simply updating History.md) I'd find it tedious to always create a branch / wait for tests to finish / etc.

:+1: regarding integration of `flake8` into CI.
