### ISSUE TITLE
Incorrect property inheritance

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#71]
Properties seem to be inherited incorrectly in Scour. Here's the declaration in the example file gnome-dev-pcmcia.svg:

  <g
    [...] id="text5059"
    style="[...];fill:none;stroke:black;stroke-width:0.99067909px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1">
    <path
       [...] id="path3675"
       style="[...];fill:white;fill-opacity:1;stroke:none;[...]" />

But the path ends up with stroke:black due to incorrect inheritance rules. The text PCMCIA, described by the above-named path in the example file, is then black instead of white.

[Inferred information from bug 702423]
Scour version used = trunk r206
Command line used = scour.py --disable-style-to-xml -i INFILE -o OUTFILE

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-03-12T20:34:32Z
 * owner: louis-simard-deactivatedaccount
 * the launchpad url was https://bugs.launchpad.net/bugs/734019

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)
[Test case imported from bug 702423]

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)
Set to Confirmed because I see what the changed declaration is.

Priority set to High because this bug corrupts documents.

**Comment by launchpad-issue-importer** [comment]
(by vish)
In addition to the gnome-dev-pcmcia.svg, i found 3 other icons which were similarly affected:
/../devices/48/gnome-dev-jazdisk.svg
/../devices/48/gnome-dev-media-cf.svg
/../devices/48/gnome-dev-zipdisk.svg

All of them with text problems.

**Comment by launchpad-issue-importer** [comment]
(by vish)

**Comment by launchpad-issue-importer** [comment]
(by eduard-braun2)
Another testcase, same problem:

<g style="stroke:#000000;stroke-width:2.8">
    <path id="1" style="fill:#da121a" d="..." />
    <path id="2" style="fill:#fcdd09;stroke:none" d="..." />
  </g>

"stroke:none" is stripped from path 2, therefore it inherits the black stroke from the parent.

**Comment by launchpad-issue-importer** [comment]
(by jazzynico)
Upstream report: https://github.com/codedread/scour/issues/22

**Comment by Ede123** [comment]
Already imported as #22.
