### ISSUE TITLE
's' command causes problems with some renderers; 'C' becomes 's' even if it describes a straight line

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#75]
The file fulltests/cgmail.svg, originally from Ubuntu 10.04's /usr/share/app-install/icons/cgmail.svg and added to trunk revision 181, renders incorrectly after being Scoured.

-- To reproduce --

Program version: trunk revision 180

Command line: ./scour.py --shorten-ids --enable-id-stripping --create-groups --renderer-workaround --indent=none -i fulltests/cgmail.svg -o fulltests/cgmail.opt.svg

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-07-10T13:46:33Z
 * owner: louis-simard-deactivatedaccount
 * the launchpad url was https://bugs.launchpad.net/bugs/603987

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)

**Comment by launchpad-issue-importer** [comment]
(by codedread)
1) The uploaded SVG does not seem to have the problem indicated in the PNG when looking at it with Firefox or Chrome.

2) I do not have a --create-groups option.  You seem to be using a development version or private branch of scour?

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)
1) True. The render was made with rsvg, and the bug does not appear in Firefox or Chrome. This will have to go into --renderer-workaround and be filed as a bug against librsvg perhaps.

2) It's in the trunk. Update your trunk directory to at least revision 180.

**Comment by launchpad-issue-importer** [comment]
(by codedread)
$ bzr up
Tree is up to date at revision 176 of branch
/Users/jeffschiller/Documents/scour

hmmm

On Sat, Jul 10, 2010 at 9:00 AM, Cynthia Gauthier <<email address hidden>
> wrote:

> 1) True. The render was made with rsvg, and the bug does not appear in
> Firefox or Chrome. This will have to go into --renderer-workaround and
> be filed as a bug against librsvg perhaps.
>
> 2) It's in the trunk. Update your trunk directory to at least revision
> 180.
>
> --
> Bad render: fulltests/cgmail.png
> https://bugs.launchpad.net/bugs/603987
> You received this bug notification because you are a member of Scouring
> Pads, which is the registrant for Scour.
>
> Status in Scour - Cleaning SVG Files: New
>
> Bug description:
> The file fulltests/cgmail.svg, originally from Ubuntu 10.04's
> /usr/share/app-install/icons/cgmail.svg and added to trunk revision 181,
> renders incorrectly after being Scoured.
>
> -- To reproduce --
>
> Program version: trunk revision 180
>
> Command line: ./scour.py --shorten-ids --enable-id-stripping
> --create-groups --renderer-workaround --indent=none -i fulltests/cgmail.svg
> -o fulltests/cgmail.opt.svg
>
>
>

**Comment by launchpad-issue-importer** [comment]
(by codedread)
Ah, just did 'bzr pull' and that brought me up to date, thanks.

Jeff

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)
'bzr pull' :) [or 'bzr pull lp:scour']

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)
lack of refresh + trying to track the bug down = my worst enemy

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)
The next-to-last element in the original file's <svg> is a <path> element. Its data contain

  L 21.448701,5.4508678 C 21.448701,5.4508678 7.4009628,17.714589 7.4009628,17.714589

, which becomes

  v-8.0991s-14.048 12.264-14.048 12.264

when passed through Scour. There are two things to note here:

1. This CurveTo makes a straight line, but it becomes a smooth Bézier curve instead of a relative LineTo (l).
2. The SmoothCurve command might be mishandled by librsvg when the previous command makes a straight line.

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)
Importance downgraded because this bug only really affects a single renderer, and the 's' commands created from straight 'C's are otherwise functionally equivalent.

**Comment by Ede123** [comment]
Scoured path data in current trunk:

v-8.0991l-14.048 12.264 14.048 12.944

Seems to have been fixed (or at least changed)

Also librsvg seems to render the original (scoured) testfile fine now, so I think it's safe to consider the issue fixed.
