### ISSUE TITLE
wishlist: Progress meter for large SVG files

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#77]
Is it possible to have scour support some kind of verbose output mode, where information such as "progress" is provided?

Thanks!

---

Imported from Launchpad using lp2gh.
- date created: 2009-11-30T04:45:33Z
- owner: mycae
- the launchpad url was https://bugs.launchpad.net/bugs/490197

**Comment by launchpad-issue-importer** [comment]
(by codedread)
This is a good suggestion - can you provide any more details on this requirement?

Would it be enough to just print out what step scour is at some level of detail, ie

Step  1 of 15: Removed unwanted namespaced elements
Step  2 of 15: Removed unwanted namespaced attributes
Step  3 of 15: Removed redundant namespace prefixes
Step  4 of 15: Removed unnecessary style properties and moved to XML attributes
Step  5 of 15: Converted colors
:

Note that even with the above, each step could take an unknown amount of time, since the structure of each file determine how long it will take, and each file is different.

Would it be useful for this to be a non-default mode, ie something you have to explicitly enable (--verbose) or do you recommend this to be the default?  I would have to use stderr to print out this information as scour may be printing to stdout if no -o argument is supplied.

**Comment by launchpad-issue-importer** [comment]
(by mycae)
> Would it be enough to just print out what step scour is at some level of detail, ie

Well, where I was coming from was that I had generated some 2D plots with scilab, which, when exported to SVG are ridiculously huge (1.8MB), however I want to keep them at print quality, so I ran scour. I came back three hours later and it was still running.

If you want super-awesomeness, a wget style 0[======>                                 ]100% meter would be perfect, which is something along the lines of:

Step (1/15) 0 [===================>  ] 100%

however I am not sure how portable this is across mutliple terminals. At the very least your suggestion would be nice.


I would suggest that this need be explicitly enabled, and would be written to stderr. Does this work on windows though? Do they have a separation of stdout/stderr ? For windows you may need to force the usage of -o.

Thanks!

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)
Windows consoles do have stderr.

Your suggestion could be done portably, if done like codedread suggests:

[1/15] Removing unwanted namespaces (no newline)

then

(Done in X.XX s) (newline)

etc. until the end of the steps.

I did a lot of optimisations in time for Scour in lp:~louis-simard/scour/rework, i.e. it runs much faster for a variety of files now. This suggestion could still have some use when the files are huge like the one you processed, but less so. Do you still have the file you processed and wanted a progress bar for?

**Comment by launchpad-issue-importer** [comment]
(by mycae)
Sorry about the delay, I meant to do this, but only came across this again today.

**Comment by launchpad-issue-importer** [comment]
(by louis-simard-deactivatedaccount)
So I just ran the latest Scour on your file with the 'time' utility, on a 2.6 GHz AMD processor, with DDR2 800 MHz, running 32-bit Linux.

real	55m54.557s
user	53m19.344s
sys	0m19.781s

If the specs of my computer and yours are comparable (core count aside, because Scour is a single-threaded program), the latest Scour is 3 times faster than the version you used. But you've hit a hard spot of Scour's with that file, and perhaps this should be optimised first before considering adding a progress option :)

I concentrated on optimising Scour's path optimisation to make it faster, and didn't pay a lot attention to polygons. That file is full of them.

So I've opened bug 616150 for the optimisation of polygon optimisation. Please follow that bug if you're interested in getting progress on that. This thread will continue to be about progress reporting.

**Comment by Ede123** [comment]
Wow, scouring the original testfile on my machine takes less then 10 seconds...
Seems Scour and Python got a lot more efficient and PCs a lot faster during the last 6 years.

Considering that most files I scour are done in only a few tens of milliseconds and even [one of the worst real world scenarios](https://upload.wikimedia.org/wikipedia/commons/archive/5/54/20120822053933%21MediaWiki_logo_1.svg) I found so far is processed in under a minute I guess the necessity for a progress bar is greatly diminished these days.

Aside from the fact that any file that large is probably unsuited to be expressed as an SVG to start with and also will be almost impossible to handle in every common software, I also think that this is a mostly unnecessary feature and (if an issue at all) the effort would be better spent improving performance of the code.

I therefore vote to close...

**Comment by nthykier** [comment]
@Ede123: Do you still get under a minute for MediaWiki_logo_1.svg? 

My benchmarks with the current master branch is closer to 105s (~1m 45s) when I use scour with no options.  Running with python3 -m profile has taken over 30 minutes (after which point, I gave up), so I do not have any accurate estimates of what is taking up all the compute power.

**Comment by nthykier** [comment]
I have created #170 to reduce the runtime pm MediaWiki_logo_1.svg by about 20s (25%) for me.

**Comment by Ede123** [comment]
> Do you still get under a minute for MediaWiki_logo_1.svg?

Yes, in Python 3.6.4 the file is processed in 40 s.  
Python 2.7.14 is significantly slower and requires 2 m 40 s.

**Comment by nthykier** [comment]
Should we close this issue?  To my knowledge, all reported images in this bug are now optimized (on master at least, with the MediaWiki_logo_1.svg case being resolved by #171 and is now less than 20s for me with python3).

**Comment by Ede123** [comment]
Absolutely, I cast my vote a year ago and nobody objected since. ;-)
