### ISSUE TITLE
Provide a way to remove whitespace (including newlines)

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#78]
--indent=none option already removes whitespace but not newlines. It would be helpful to be able to remove _all_ insignificant whitespace from the file.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-01-19T21:26:02Z
 * owner: kangax
 * the launchpad url was https://bugs.launchpad.net/bugs/705127

**Comment by Ede123** [comment]
Implemented in Scour 0.31, see e21e36235346b509829143e097fe4fceabfef113
