### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#81]
Getting an error when running the command
python scour.py -i input.svg -o output.svg

Even if i only run "python scour.py" there is the same error.
Running on Win XP, python 2.4.1, scour 0.26. It's the first time i use a python script, may be the problem is in front of the pc..
Error:

  File "scour.py", line 2712
    return ''.join([xml_ents[c] if c in xml_ents else c for c in str])
                                 ^
SyntaxError: invalid syntax

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-07-13T10:15:20Z
 * owner: kartografie
 * the launchpad url was https://bugs.launchpad.net/bugs/809783

**Comment by Ede123** [comment]
This was probably an incompatibility with Python 2.4.1 or is fixed in the meantime.
