### ISSUE TITLE
circle cx/cy attributes in % get stripped

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#83]
An svg such as Japan.svg:

<svg xmlns="http://www.w3.org/2000/svg">
 <circle fill="red" cy="50%" cx="50%" r="25%"/>
</svg>

should not be affected by scour. Currently, cx and cy are dropped. I assume other tags and attributes might be affected too.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-07-24T05:16:19Z
 * owner: ecmanaut
 * the launchpad url was https://bugs.launchpad.net/bugs/815287

**Comment by launchpad-issue-importer** [comment]
(by jazzynico)
Reproduced with Inkscape trunk revision 10466 (scour 0.26).

**Comment by Ede123** [comment]
Will be fixed in the next version, see #70 .
