### ISSUE TITLE
Unnecessary metadata is inserted in the root element SVG

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#84]
The option "remove metadata" leavs the declaration in the head. <svg xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"   xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/"

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-12-18T12:13:37Z
 * owner: arachnovobia
 * the launchpad url was https://bugs.launchpad.net/bugs/905919

**Comment by Ede123** [comment]
Fixed in Scour 0.32, see #14
