### ISSUE TITLE
Sample SVG file.

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#86]
In the home page is a request for sample files.  One is available here.
https://secure.wikimedia.org/wikipedia/commons/wiki/File:CategoricalProduct0x0Test0.svg

Regards,       ... Peter E.,  peasthope at shaw.ca

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2012-10-05T16:44:17Z
 * owner: peasthope
 * the launchpad url was https://bugs.launchpad.net/bugs/1062418

**Comment by Ede123** [comment]
Not an issue.

(I even verified the scoured file looks identical to the original)
