### ISSUE TITLE
Percents make scour crash

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#88]
komachi@onozuka:~$ scour -i bw.svg -o bw2.svg
scour 0.26
Copyright Jeff Schiller, Louis Simard, 2010
Traceback (most recent call last):
  File "/usr/bin/scour", line 3186, in <module>
    out_string = scourString(in_string, options).encode("UTF-8")
  File "/usr/bin/scour", line 2880, in scourString
    numStylePropsFixed = repairStyle(doc.documentElement, options)
  File "/usr/bin/scour", line 1378, in repairStyle
    fillOpacity = float(styleMap['fill-opacity'])
ValueError: invalid literal for float(): 14.1176%

SVG file attached.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-01-09T18:53:35Z
 * owner: komachi-onozuka
 * the launchpad url was https://bugs.launchpad.net/bugs/1097882

**Comment by launchpad-issue-importer** [comment]
(by komachi-onozuka)

**Comment by launchpad-issue-importer** [comment]
(by jazzynico)
According to the SVG specs, fill-opacity should not use percentages...
See http://www.w3.org/TR/SVG/painting.html#FillProperties

**Comment by Ede123** [comment]
As jazzynico noted, `fill-opacity` expects a number (at least if specified as a property).

Even as a CSS declaration (as is the case here) a number is expected. Percentages [https://drafts.csswg.org/css-color/#transparency](might be allowed) at a point in the future, but certainly nothing to be worried about now.
