### ISSUE TITLE
Error in path simplification algorithm breaks output paths: "c0 0" curveto curve command stripped

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#91]
The path simplification algorithm strips "c0 0" commands from the path. The output looks quite different as a result.

See the attached testcase for an example:
 - a.svg = SVG file before scouring
 - b.svg = SVG file after scouring

Look at beak and claws for the visual difference.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-05-20T23:40:55Z
 * owner: eduard-braun2
 * the launchpad url was https://bugs.launchpad.net/bugs/1182267

**Comment by launchpad-issue-importer** [comment]
(by eduard-braun2)

**Comment by launchpad-issue-importer** [comment]
(by eduard-braun2)

**Comment by launchpad-issue-importer** [comment]
(by eduard-braun2)

**Comment by Ede123** [comment]
Fixed in #110.
