### ISSUE TITLE
Invalid SVG output with text attributes

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#94]
If you have text and the option convert CSS attributes to XML, the SVG code get invalid (as the W3C Validator says http://validator.w3.org/#validate_by_upload).: "Attribute line-height not allowed on SVG element " (the same with text-align) It seems that this are only CSS attributes and not SVG/XML attributes.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-12-14T01:30:06Z
 * owner: perhelion1
 * the launchpad url was https://bugs.launchpad.net/bugs/1402320

**Comment by launchpad-issue-importer** [comment]
(by jazzynico)
Confirmed when saving from Inkscape trunk rev. 13836 (Scour rev. 222). See attached test file.

Moving the line-height attribute to the style attribute fixes the issue. Note that the text-align attribute (as well as text-anchor, writing-mode, word-spacing and letter-spacing) is not converted to XML attribute.

**Comment by launchpad-issue-importer** [comment]
(by jazzynico)

**Comment by Ede123** [comment]
Fixed in #99.

We were missing a lot of presentation attributes while wrongly converting `line-height` and `visibility`.
