### ISSUE TITLE
Quoted font-family-names get destroyed (by Scour)

### ISSUE THREAD

**Issue by launchpad-issue-importer** [scour-project/scour#95]
This is a longe-time bug (I found no report). Font-family-names like "'MyriadPro-Regular'" get converted to "&apos;MyriadPro-Regular&apos;" with HTML-Entitys (primary fonts with whitespaces, because single quotation marks are recommended for this by the W3C) if you save as Optimzed SVG. Tested on Windows 7 x64 and Ubuntu latest version. Upstream as bug 1514075

=====
Inkscape 0.91 r13725
includes Scour 0.26+r220
https://bazaar.launchpad.net/~inkscape.dev/inkscape/RELEASE_0_91_BRANCH/view/13725/share/extensions/scour.py#L76

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-12-05T06:45:57Z
 * owner: jazzynico
 * the launchpad url was https://bugs.launchpad.net/bugs/1514073

**Comment by launchpad-issue-importer** [comment]
(by suv-lp)
Please add information about OS/platform and Inkscape version to the bug description, and attach a test case (Inkscape SVG file).

**Comment by launchpad-issue-importer** [comment]
(by perhelion1)
Hej suv, as described the OS/platform seems here unattached. Here a test-case attached (I mean the problem could be in the Scour Python module):

**Comment by launchpad-issue-importer** [comment]
(by suv-lp)
"Tested on Windows 7 x64 and Ubuntu latest version" gives no clue whatsoever which Inkscape version was used (For example: different releases of Ubuntu include different versions of Inkscape which may include different versions of Scour).

Please add information about Inkscape to the bug description as requested.

**Comment by launchpad-issue-importer** [comment]
(by suv-lp)
Reproduced on OS X 10.7.5 with current trunk Inkscape 0.91+devel r14449
(includes Scour 0.26+r220)

Reduced test case (created with Inkscape, default new doc, default (new)
prefs) attached:
1) create regular text object
2) set font family to 'Times New Roman'
3) save as Inkscape SVG
4) save a copy as 'Optimized SVG'
(all options unchecked, pretty-printing set to 'None')

**Comment by launchpad-issue-importer** [comment]
(by suv-lp)
So far, I did not find an SVG viewer which would misrender text in such a scoured SVG file though (Chromium 48.0.2556.0, Firefox 41.0.2, Batik 1.7.1, rsvg-view-3 (from librsvg 2.40.11), as well as Inkscape use the expected font to render the text on-canvas).

**Comment by launchpad-issue-importer** [comment]
(by perhelion1)
Okay, but that is no reason (error correction can handle this) to ignore this bug (I'm sure someone old viewer/editor can't handle this). 
I made another example to show more aftereffects, for example fallback-fonts get prior. Also other optimzation scripts (and Scour himself) can't not handle this defect code optimal anymore.

**Comment by launchpad-issue-importer** [comment]
(by jazzynico)
Also reproduced on Xunbuntu 15.10, with Inkscape 0.91 (scour 0.26) and the latest standalone Scour version (0.31).

Reported upstream (https://github.com/codedread/scour/issues/21).

**Comment by Ede123** [comment]
Already imported as #21.
